language: cpp
sudo: required
compiler:
   - clang
   - gcc
os:
   - linux 
script:
   - mkdir build 
   - cd build 
   - cmake ..
   - make
before_install:
   #install newer cmake
   - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz -O cmake.tar.gz; fi
   - if [ "$TRAVIS_OS_NAME" = "linux" ]; then tar -xzf cmake.tar.gz -C $HOME; fi
   - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PATH=$HOME/cmake-3.3.2-Linux-x86_64/bin:$PATH; fi
   - sudo apt-get -qq update
   - sudo apt-get install -y libfreetype6-dev libopenal-dev

   # workaround for Clang
   - $CC --version
   - which $CC
   - export CC=`which $CC`

   - wget http://www.libsdl.org/release/SDL2-2.0.5.tar.gz
   - tar xzf SDL2-2.0.5.tar.gz
   - cd SDL2-2.0.5
   - ./configure --prefix=/usr 
   - sudo make -j5 
   - sudo make install
   - cd ..
   - wget http://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
   - tar xzf SDL2_image-2.0.1.tar.gz
   - cd SDL2_image-2.0.1 
   - ./configure --prefix=/usr 
   - sudo make -j5 
   - sudo make install
   - cd ..

   # Ogg
   - wget http://downloads.xiph.org/releases/ogg/libogg-1.3.2.tar.gz
   - tar xzf libogg-1.3.2.tar.gz
   - cd libogg-1.3.2
   - ./configure --prefix=/usr
   - make -j5
   - sudo make install
   - cd ..

   # Vorbis
   - wget http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.5.tar.gz
   - tar xzf libvorbis-1.3.5.tar.gz
   - cd libvorbis-1.3.5
   - ./configure --prefix=/usr
   - make -j5
   - sudo make install
   - cd ..

   # Must build Kobold too
   - git clone https://github.com/farrer/kobold.git
   - cd kobold
   - mkdir build
   - cd build
   - cmake ..
   - make -j5
   - sudo make install
   - cd ../../
